<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>NewsletterWebApi</RootNamespace>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

    <PropertyGroup>
        <NoWarn>1591</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.3.0" />
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer" Version="5.1.0" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.0" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.0" />
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning" Version="5.1.0" />
        <PackageReference Include="AspNetCore.HealthChecks.Npgsql" Version="8.0.2" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="7.1.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../NewsletterSDK/NewsletterSDK.csproj" />
    </ItemGroup>

</Project>
