name: Deploy to Server

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
        shell: bash

      - name: Pull and run the Docker image on the server
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
        run: |
          ssh -p $SSH_PORT $SSH_USER@$SSH_HOST "
            cd /home/$SSH_USER/apps/newsletter-api || mkdir -p /home/$SSH_USER/apps/newsletter-api && cd /home/$SSH_USER/apps/newsletter-api

            echo 'Logging in to GHCR...'
            echo '${{ secrets.GITHUB_TOKEN }}' | sudo docker login ghcr.io -u '${{ github.actor }}' --password-stdin

            echo 'Pulling latest image...'
            sudo docker pull ghcr.io/igor-couto/newsletter:latest

            echo 'Stopping and removing any old container...'
            sudo docker rm -f newsletter-api || true

            echo 'Running the container...'
            sudo docker run -d \
              --name newsletter-api \
              --restart=always \
              -p 50040:50040
              ghcr.io/igor-couto/newsletter:latest
          "
        shell: bash