name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Check out source
        uses: actions/checkout@v4

      - name: Log in to container registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          docker build -f NewsletterWebApi/Dockerfile -t ghcr.io/igorcouto/newsletter-api:latest .
    
      - name: Push Docker image
        run: |
          docker push ghcr.io/igorcouto/newsletter-api:latest
