name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU (for cross-building)
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up BuildX
        uses: docker/setup-buildx-action@v3

      - name: Check out source
        uses: actions/checkout@v4

      - name: Log in to container registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker image for ARM64
        run: |
          docker buildx build \
            --platform linux/arm64 \
            -f NewsletterWebApi/Dockerfile \
            -t ghcr.io/igorcouto/newsletter-api:latest \
            --push \
            .
