name: Tests

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - 'CODE_OF_CONDUCT.md'
      - 'SECURITY.md'
      - 'LICENCE.md'
      - 'docs/**'

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:

      - name: 🛠️ Checkout Repository
        uses: actions/checkout@v4

      - name: ⚙️ Setup .NET 9 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x

      - name: 🧪 Testing
        run: |
          cd Tests/
          dotnet test